version: "3.7" 
 
networks: 
  loki: 
 
services: 
  loki: 
    image: grafana/loki 
    ports: 
      - "3100:3100" 
    command: -config.file=/etc/loki/local-config.yaml 
    networks: 
      - loki 
  
  grafana: 
    image: grafana/grafana:latest 
    ports: 
    - "3000:3000" 
    networks: 
    - loki 